In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing

In [ ]:
cis = pd.read_csv(r"C:\Users\amira\Downloads\testbed_system_1_network_aggregated.csv")
cis

,bucket,system_id,protocol,avg_size,source_total_packets,destination_total_packets,min_size,max_size,num_connections,source_ip,source_port,source_mac,destination_ip,destination_port,destination_mac,source_key,destination_key,source_asset,destination_asset
0,2021-04-09 11:30:30+00:00,testbed_system_1,TCP,60.857143,51,120,60,66,7,84.3.251.18,502.0,00:80:f4:03:fb:12,84.3.251.101,38055.0,e6:3f:ac:c9:a8:8c,84.3.251.18,84.3.251.101,NaN,NaN
1,2021-04-09 11:30:30+00:00,testbed_system_1,TCP,71.600000,73,10,66,78,5,84.3.251.102,502.0,0a:fe:ec:47:74:fb,84.3.251.104,58691.0,4a:35:83:e0:3d:a4,84.3.251.102,84.3.251.104,NaN,NaN
2,2021-04-09 11:30:30+00:00,testbed_system_1,TCP,60.000000,42,103,60,60,6,84.3.251.18,502.0,00:80:f4:03:fb:12,84.3.251.101,59827.0,e6:3f:ac:c9:a8:8c,84.3.251.18,84.3.251.101,NaN,NaN
3,2021-04-09 11:30:30+00:00,testbed_system_1,TCP,60.857143,44,121,60,66,7,84.3.251.18,502.0,00:80:f4:03:fb:12,84.3.251.101,46691.0,e6:3f:ac:c9:a8:8c,84.3.251.18,84.3.251.101,NaN,NaN
4,2021-04-09 11:30:30+00:00,testbed_system_1,TCP,68.666667,103,105,66,74,6,84.3.251.102,54587.0,0a:fe:ec:47:74:fb,84.3.251.101,502.0,e6:3f:ac:c9:a8:8c,84.3.251.102,84.3.251.101,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352211,2022-02-21 15:13:30+00:00,testbed_system_1,TCP,60.000000,0,54,60,60,1,84.3.251.20,20043.0,00:0c:29:47:8c:0e,84.3.251.18,502.0,00:80:f4:03:fb:12,84.3.251.20,84.3.251.18,NaN,NaN
352212,2022-02-21 15:13:30+00:00,testbed_system_1,TCP,60.000000,0,55,60,60,1,84.3.251.20,24650.0,00:0c:29:47:8c:0e,84.3.251.18,502.0,00:80:f4:03:fb:12,84.3.251.20,84.3.251.18,NaN,NaN
352213,2022-02-21 15:13:30+00:00,testbed_system_1,TCP,60.000000,0,55,60,60,1,84.3.251.20,22935.0,00:0c:29:47:8c:0e,84.3.251.18,502.0,00:80:f4:03:fb:12,84.3.251.20,84.3.251.18,NaN,NaN
352214,2022-02-21 15:13:30+00:00,testbed_system_1,TCP,60.000000,0,55,60,60,1,84.3.251.20,20686.0,00:0c:29:47:8c:0e,84.3.251.18,502.0,00:80:f4:03:fb:12,84.3.251.20,84.3.251.18,NaN,NaN
352215,2022-02-21 15:13:30+00:00,testbed_system_1,TCP,60.000000,0,11,60,60,2,84.3.251.18,502.0,00:80:f4:03:fb:12,84.3.251.20,1290.0,74:46:a0:bd:a7:1b,84.3.251.18,84.3.251.20,NaN,NaN

In [3]:
cis.groupby(by=['destination_ip']).size()

destination_ip
84.3.251.101     60131
84.3.251.102     43606
84.3.251.103     29621
84.3.251.104      9448
84.3.251.105      9349
84.3.251.110        13
84.3.251.18     194207
84.3.251.20       5546
dtype: int64

In [5]:
cis["avg_size"].mean()

np.float64(64.75035944874662)

In [ ]:

cis.describe()

,avg_size,source_total_packets,destination_total_packets,min_size,max_size,num_connections,source_port,destination_port,source_asset,destination_asset
count,352216.000000,3.522160e+05,3.522160e+05,352216.000000,352216.000000,3.522160e+05,351852.000000,351852.000000,0.0,0.0
mean,64.750359,2.706656e+03,3.282224e+03,63.599348,66.605222,8.256279e+01,25092.643819,13531.056970,NaN,NaN
std,10.225423,3.226190e+05,3.282154e+05,9.498452,11.385492,3.486456e+03,21959.765926,21266.964857,NaN,NaN
min,60.000000,0.000000e+00,0.000000e+00,60.000000,60.000000,1.000000e+00,0.000000,25.000000,NaN,NaN
25%,60.000000,0.000000e+00,1.700000e+01,60.000000,60.000000,1.000000e+00,502.000000,502.000000,NaN,NaN
50%,60.000000,7.000000e+00,8.100000e+01,60.000000,60.000000,2.000000e+00,22345.000000,502.000000,NaN,NaN
75%,69.142857,4.400000e+01,1.100000e+02,66.000000,74.000000,5.000000e+00,45525.000000,35637.000000,NaN,NaN
max,1514.000000,1.658059e+08,1.658118e+08,1514.000000,1514.000000,1.714038e+06,65535.000000,61646.000000,NaN,NaN